'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CUSTOMER
    Public Property USERID As Nullable(Of Integer)
    Public Property ID As Integer
    Public Property ORDER_ID As Nullable(Of Integer)
    Public Property ADRESS As String
    Public Property PHONE As String
    Public Property EMAIL As String
    Public Property F_NAME As String
    Public Property L_NAME As String

    Public Overridable Property ORDER As ORDER
    Public Overridable Property USER As USER
    Public Overridable Property ORDER1 As ICollection(Of ORDER) = New HashSet(Of ORDER)

End Class
