'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DELIVERY
    Public Property ID As Integer
    Public Property ROUTE_ID As Nullable(Of Integer)
    Public Property STATUS_D As Nullable(Of Boolean)
    Public Property F_NAME As String
    Public Property L_NAME As String
    Public Property PHONE As String
    Public Property NUM_HOURS As Nullable(Of Integer)
    Public Property EMAIL As String

    Public Overridable Property ROUTE As ROUTE
    Public Overridable Property ROUTE1 As ICollection(Of ROUTE) = New HashSet(Of ROUTE)

End Class
