'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ORDER
    Public Property ID As Integer
    Public Property PACKAGE_NUMBER As Nullable(Of System.Guid)
    Public Property ORDER_STATUS As Nullable(Of Integer)
    Public Property BOXES_AMOUNT As Nullable(Of Integer)
    Public Property DEADLINE_DATE As Nullable(Of Date)
    Public Property ROUTE_ID As Nullable(Of Integer)
    Public Property CUSTOMER_ID As Nullable(Of Integer)

    Public Overridable Property CUSTOMER As ICollection(Of CUSTOMER) = New HashSet(Of CUSTOMER)
    Public Overridable Property CUSTOMER1 As CUSTOMER
    Public Overridable Property ROUTE As ROUTE
    Public Overridable Property ROUTE1 As ICollection(Of ROUTE) = New HashSet(Of ROUTE)

End Class
