'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ROUTE
    Public Property ID As Integer
    Public Property ORDER_ID As Nullable(Of Integer)
    Public Property DELIVERY_ID As Nullable(Of Integer)

    Public Overridable Property DELIVERY As ICollection(Of DELIVERY) = New HashSet(Of DELIVERY)
    Public Overridable Property DELIVERY1 As DELIVERY
    Public Overridable Property ORDER As ICollection(Of ORDER) = New HashSet(Of ORDER)
    Public Overridable Property ORDER1 As ORDER
    Public Overridable Property USER As ICollection(Of USER) = New HashSet(Of USER)

End Class
